USE WAREHOUSE URBANFLOW_WH;
USE DATABASE URBANFLOW;
USE SCHEMA GOLD;

CREATE OR REPLACE STAGE GOLD_STAGE
  STORAGE_INTEGRATION = URBANFLOW_S3_INT
  URL = 's3://urbanflow-datalake-dev-us-east-1-139961319000/urbanflow/gold/'
  FILE_FORMAT = (TYPE = PARQUET);