CREATE OR REPLACE TABLE VIAGENS_RESUMO_HORA (
    STATUS VARCHAR,
    FONTE VARCHAR,
    QTD_REGISTROS NUMBER,
    QTD_VIAGENS_DISTINTAS NUMBER,
    QTD_PASSAGEIROS_DISTINTOS NUMBER,
    QTD_MOTORISTAS_DISTINTOS NUMBER,
    PRECO_MEDIO FLOAT,
    PRECO_TOTAL FLOAT,
    GOLD_PROCESS_TS TIMESTAMP_NTZ,
    HORA NUMBER,
    ANO NUMBER,
    MES NUMBER,
    DIA NUMBER
);
