USE WAREHOUSE URBANFLOW_WH;
USE DATABASE URBANFLOW;
USE SCHEMA GOLD;

LIST @GOLD_STAGE;

SELECT COUNT(*) AS total_registros
FROM VIAGENS_RESUMO_HORA;

SELECT *
FROM MART_VIAGENS_DIARIAS
ORDER BY data DESC;